experiment:
  # machine setting, optional: cuda, cpu
  device: CPU
  # dataset setting
  dataset_name: KnowAir
  used_feature_params: ['2m_temperature',
               'relative_humidity+950',
               'boundary_layer_height',
               'k_index',
               'surface_pressure',
               'total_precipitation',
               'hour',
               'weekday',
               'month',
               'wind_speed',
               'wind_direction']
  # 1: normalize, 2: embedding
  feature_process: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
  # progress setting
  save_npy: True
  # model setting, optional: ADAIN
  model_name: ADAIN
  # train seed, 0 means random
  seed: 1
  # dataloader num worker
  num_workers: 12

# general filepath
filepath:
  Local:
    dataset_dir: D:\Project\AirGAN\data
    records_dir: D:\Project\AirGAN\records
    results_dir: D:\Project\AirGAN\results

general_hyper_params:
  seq_len: 24
  batch_size: 64
  epochs: 50
  exp_times: 1
  weight_decay: 0.5
  lr: 0.0005
  is_early_stop: True
  early_stop: 10
# model hyperparameters setting
model_hyper_params:
  ADAIN:
    dropout: 0.1