# general hyperparameters setting
general_hyper_params:
  hist_len: 8
  pred_len: 24
  batch_size: 200
  epochs: 300
  exp_times: 1
  weight_decay: 0.001
  lr: 0.001
  is_early_stop: True
  early_stop: 10
# model hyperparameters setting
model_hyper_params:
  # 1: normalize, 2: embedding
  feature_process: [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
  AECGAN:
    hidden_dim: 50
    noise_type: min_adv
    use_ec: 2