# general hyperparameters setting
general_hyper_params:
  hist_len: 24
  pred_len: 24
  batch_size: 64
  epochs: 100
  exp_times: 1
  weight_decay: 0.0001
  lr: 0.001
  is_early_stop: False
  early_stop: 10
# model hyperparameters setting
model_hyper_params:
  # 1: normalize, 2: embedding
  feature_process: [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
  DGCRN:
    rnn_size: 64
    gnn_dim: 16
    prop_alpha: 0.05
    gcn_depth: 2
    dropout: 0.3
    clip: 5
    tanh_alpha: 3
    step_size: 2500
    node_dim: 40
