# general hyperparameters setting
general_hyper_params:
   # 24, 8
  hist_len: 8
  # 24, 8
  pred_len: 8
  # 512 2048
  batch_size: 2048
  epochs: 50
  exp_times: 1
  weight_decay: 0.0001
  lr: 0.0001
  is_early_stop: True
  early_stop: 5
# model hyperparameters setting
model_hyper_params:
  # 1: normalize, 2: embedding
#  feature_process: [ 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1 ]
  SimST:
    hidden_dim: 64
    dropout: 0.2
    clip: 5
    gru_layers: 2
    use_dynamic: True
