experiment:
  # machine setting, optional: cuda, cpu
  device: cuda
  # dataset setting
  dataset_name: KnowAir
  used_feature_params: ['2m_temperature',
               'relative_humidity+950',
               'boundary_layer_height',
               'k_index',
               'surface_pressure',
               'total_precipitation',
               'hour',
               'weekday',
               'month',
               'wind_speed',
               'wind_direction']
  # 1: normalize, 2: embedding
  feature_process: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
  train_start: [ [ 2015, 1, 1 ], GMT ]
  train_end: [ [ 2016, 12, 31 ], GMT ]
  valid_start: [ [ 2017, 1, 1 ], GMT ]
  valid_end: [ [ 2017, 12, 31 ], GMT ]
  test_start: [ [ 2018, 1, 1 ], GMT ]
  test_end: [ [ 2018, 12, 31 ], GMT ]
  # progress setting
  save_npy: True
  # model setting, optional: MLP, GRU, GC_LSTM, PM25_GNN, GAGNN, AirFormer, SimST
  model_name: GAGNN
  # train seed, 0 means random
  seed: 1
  # dataloader num worker
  num_workers: 12

# general filepath
filepath:
  Local:
    dataset_dir: D:\Project\AirGAN\data
    records_dir: D:\Project\AirGAN\records
    results_dir: D:\Project\AirGAN\results

# dataset info
KnowAir:
  data_start: [ [ 2015, 1, 1, 0, 0 ], GMT ]
  data_end: [ [ 2018, 12, 31, 21, 0 ], GMT ]
  time_span_hour: 3
  city_num: 184
  feature_params:
    ['100m_u_component_of_wind',
     '100m_v_component_of_wind',
     '2m_dewpoint_temperature',
     '2m_temperature',
     'boundary_layer_height',
     'k_index',
     'relative_humidity+950',
     'relative_humidity+975',
     'specific_humidity+950',
     'surface_pressure',
     'temperature+925',
     'temperature+950',
     'total_precipitation',
     'u_component_of_wind+950',
     'v_component_of_wind+950',
     'vertical_velocity+950',
     'vorticity+950',
     'hour',
     'weekday',
     'month',
     'wind_speed',
     'wind_direction']
CityAir:
  data_start: [ [ 2017, 1, 1, 0, 0 ], GMT ]
  data_end: [ [ 2019, 4, 30, 12, 0 ], GMT ]
  time_span_hour: 1
  city_num: 209
  # Currently don't know the order of parameters and the specific meaning of a parameter
  feature_params:
    ['humidity',
     'rainfall',
     'air_pressure',
     'temperature',
     'wind_speed',
     'wind_direction'
    ]