# general hyperparameters setting
general_hyper_params:
  hist_len: 8
  pred_len: 24
  batch_size: 32
  epochs: 50
  exp_times: 1
  weight_decay: 0.0005
  lr: 0.0005
  is_early_stop: True
  early_stop: 10