# general hyperparameters setting
general_hyper_params:
  seq_len: 8
  batch_size: 64
  epochs: 50
  exp_times: 1
  weight_decay: 0.0001
  lr: 0.0001
  is_early_stop: True
  early_stop: 10
# model hyperparameters setting
model_hyper_params:
  # 1: normalize, 2: embedding
  feature_process: [ 1, 2, 1, 1, 1, 2, 2, 2, 2 ]
  NBST:
    hidden_dim: 64