general_hyper_params:
  seq_len: 24
  batch_size: 128
  epochs: 50
  exp_times: 3
  weight_decay: 0.001
  lr: 0.001
  is_early_stop: True
  early_stop: 5
# model hyperparameters setting
model_hyper_params:
  feature_process: [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
  ADAIN:
    dropout: 0.3